services:
  # https://hub.docker.com/_/redis
  redis:
    image: redis:latest
    container_name: redis_container
    ports:
      - "6379:6379"

  # https://hub.docker.com/r/redis/redisinsight
  redisinsight:
    image: redis/redisinsight:latest
    container_name: redisinsight_container
    ports:
      - "5540:5540"
    # Using Docker Network Config -> Localhost only points to its own container
    environment:
      - RI_REDIS_HOST=redis
      - RI_REDIS_PORT=6379